### ISSUE TITLE
Check USB w/ Docker

### ISSUE THREAD

**Issue by pattacini** [icub-tech-iit/test-skin-patches#3]
We need to test if the docker container can use the USB successfully to talk to the CAN device.

**Comment by davidetome** [comment]
## Update
Following @traversaro hint and after some tests and google research  I can now use the  `can0 `  ip link on the host from the `docker`:

![deepin-screen-recorder_gjs_20210210112008](https://user-images.githubusercontent.com/6638215/107496878-2aa84480-6b92-11eb-85a7-5fc869fb7482.gif)

🛑 The problem I'm facing now is that running the docker image with the `--network=host` option I can't start the `VNC` connection
 
### Resources
- https://stackoverflow.com/questions/42769011/access-non-ip-interface-in-docker-container
- https://stackoverflow.com/questions/27708376/why-am-i-getting-an-rtnetlink-operation-not-permitted-when-using-pipework-with-d
- https://man7.org/linux/man-pages/man8/ip-link.8.html
- https://forums.docker.com/t/creating-and-sharing-virtualcan-network-interface-between-docker-containers/61596
- https://developers.redhat.com/blog/2018/10/22/introduction-to-linux-interfaces-for-virtual-networking/

---
cc @pattacini

**Comment by pattacini** [comment]
So, wasn't `--device` working?
Step by step, now we'll need to sort out noVNC then 😄

**Comment by pattacini** [comment]
@davidetome my recommendation is now to:
- edit the README in the feat branch to amend the instructions and refer to the option `--network=host` instead.
- modify the Dockerfile to change references to the feat branch (it'll be master eventually)
- open up a PR to merge the feat branch into master
- fill in #4

**Comment by davidetome** [comment]
> So, wasn't --device working?

❌  I tried and googled for, but seems that the `ESD CAN` is not listed under /dev as a device to be passed
❌  I tried also [this](https://stackoverflow.com/questions/24225647/docker-a-way-to-give-access-to-a-host-usb-or-serial-device), but without success.

🔍  Now I'm trying to get VNC connection working, if you have any hints are very welcome 👍🏻

**Comment by pattacini** [comment]
> Now I'm trying to get VNC connection working, if you have any hints are very welcome 👍🏻

Unfortunately, I have no time right now ☹

**Comment by pattacini** [comment]
I would start off by seeing whether these [ports][1] are eventually available.

[1]: https://github.com/icub-tech-iit/test-skin-patches/blob/master/dockerfiles/Dockerfile#L81

**Comment by vtikha** [comment]
> > So, wasn't --device working?
> 
> ❌ I tried and googled for, but seems that the `ESD CAN` is not listed under /dev as a device to be passed
> ❌ I tried also [this](https://stackoverflow.com/questions/24225647/docker-a-way-to-give-access-to-a-host-usb-or-serial-device), but without success.
> 
> 🔍 Now I'm trying to get VNC connection working, if you have any hints are very welcome 👍🏻

If you want we can have a call and share some hints as we have dealt a bit with this while running the robot / speech / cameras on containers in the icub-head.

**Comment by davidetome** [comment]
> I would start off by seeing whether these [ports](https://github.com/icub-tech-iit/test-skin-patches/blob/master/dockerfiles/Dockerfile#L81) are eventually available.

No ports available unlike of running without `--net=host` option

![image](https://user-images.githubusercontent.com/6638215/107503899-cdfd5780-6b9a-11eb-94bc-5ea0f5762a6a.png)

**Comment by davidetome** [comment]
> If you want we can have a call and share some hints as we have dealt a bit with this while running the robot / speech / cameras on containers in the icub-head.

It should be great, @vtikha !! Thanks, please set a time by your convenience 🕐

**Comment by vtikha** [comment]
> > If you want we can have a call and share some hints as we have dealt a bit with this while running the robot / speech / cameras on containers in the icub-head.
> 
> It should be great, @vtikha !! Thanks! 👍🏻
> Please set a time by your convenience 🕐

Call scheduled for this afternoon at 16. 👍🏼

**Comment by davidetome** [comment]
Many thanks to @vtikha 🥇  who gave me some missing parameters and now I'm able to use the `GUIS` inside the docker.

Here is the `FirmwareUpdater` running inside the docker and discovering an `mtb` board via `ESD USB/CAN` attached to my laptop:

![Screenshot-20210210165232-1885x989](https://user-images.githubusercontent.com/6638215/107535059-b33dd980-6bc0-11eb-8759-267749b17a4d.png)

Here's the working command:
```xml
docker run -it --rm  -p 6080:6080 --network host --cap-add=NET_ADMIN --privileged --env DISPLAY=${DISPLAY} --env XAUTHORITY=/root/.Xauthority --mount type=bind,source=${XAUTHORITY},target=/root/.Xauthority --mount type=bind,source=${HOME}/.config/yarp,target=/root/.config/yarp ghcr.io/icub-tech-iit/test-skin-patches:latest 
```
Maybe we'll be able to let VNC also working in the next future, but at this moment this could be a first working solution.

cc @pattacini @traversaro

**Comment by pattacini** [comment]
Fantastic! Thanks @vtikha 🎉 

cc @maggia80

**Comment by maggia80** [comment]
thanks a lot @davidetome  and @vtikha for the help
