### ISSUE TITLE
Check/Enable noVNC

### ISSUE THREAD

**Issue by pattacini** [icub-tech-iit/test-skin-patches#7]
Following up on #3, we're now using GUI w/o noVNC. Anyway, noVNC provides us a full-fledged graphical environment.

To start addressing this, I've made a quick test w/ our grasping sandbox. So, I've gone through [these instructions][1] and launched in a row:
```sh
$ docker pull ghcr.io/robotology/icub-gazebo-grasping-sandbox:latest
$ docker run -it --rm --network host --user gitpod ghcr.io/robotology/icub-gazebo-grasping-sandbox:latest
```

Surprisingly, I can connect to noVNC gracefully! 💫

Before doing this, I've also checked whether the host has the port `6080` allocated by the intended noVNC python-based server via:
```sh
$ sudo netstat -tulpn | grep 6080
```
and it has it!

Given that I used `--network host`, the ports exposed by the container won't show up if you request:
```
$ docker ps -l
```
This is somehow expected, I found out.

I'm gonna do a test now with this docker image and let you know.

cc @traversaro @vtikha 

[1]: https://github.com/robotology/icub-gazebo-grasping-sandbox/blob/master/dockerfiles/README.md

**Comment by pattacini** [comment]
Working just fine... 🤔

![Screenshot 2021-02-13 163243](https://user-images.githubusercontent.com/3738070/107853980-36596c80-6e19-11eb-81cf-ab1971471c5c.png)

I've launched:
```sh
$ docker run -it --rm --network host ghcr.io/icub-tech-iit/test-skin-patches:latest
```

Am I missing something here?

**Comment by pattacini** [comment]
It's definitely working nicely here as I was able to launch `FirmwareUpdater`:

![Screenshot 2021-02-13 164608](https://user-images.githubusercontent.com/3738070/107854264-1fb41500-6e1b-11eb-815d-8dff1ccb2c7e.png)

@davidetome did you remember to launch `start-vnc-session.sh` from the container shell? 😄

I will try to launch it automatically when we start a container.

**Comment by davidetome** [comment]
🎆  @pattacini I've tested the commands on a blank VM (Ubuntu 20.04) and, differently from my machine, it worked!!!
🎗️ I'll check later why on my system I can't get connected to the docker via noVNC

![deepin-screen-recorder_VirtualBox Machine_20210215150227](https://user-images.githubusercontent.com/6638215/107956662-c32e3280-6f9f-11eb-96b2-b2cf05fe95cf.gif)

Next step, test the environment with an `mtb4` and a skin patch

cc @vtikha @maggia80

**Comment by pattacini** [comment]
@davidetome can you confirm this can be considered solved?
